### ISSUE TITLE
:hammer_and_pick: Base API endpoint for all services

### ISSUE THREAD

**Issue by jadudm** [jadudm/eight#1]
# Background

Although most communications between services will be via queue, there are things that cannot/should not be pushed through the queues. Examples:

* `/healthcheck`: Every service needs a way for CF and Docker to know if it is healthy. 
* `/meminfo`: It would be nice to have a service that queries all of the apps periodically, and keeps track of their memory usage and other performance stats.

Building this as a common component, and letting services build additional mux/routers on top of it, would guarantee that we can keep eyes on every app (and, sometimes, drive/test via HTTP/API) critical operations. For example, the `crawler` has an API endpoint for adding new jobs to the crawl queue. This is useful for dev testing, and if we need to allow users to enqueue specific pages, other components (e.g. a dashboard) can enqueue jobs via HTTP PUT as opposed to trying to interact directly with the underlying queue.

## Tasks

- [ ] Turn existing API work into a shared component
- [ ] Implement `/meminfo`
- [ ] Add `/common` into an endpoint that captures some common properties that might be of interest (see below)
- [ ] :grey_question:  Add `/specific` as an endpoint that returns a JSON of app-specific data.

 Common properties might include

* Last start
* Uptime
* API queries served
* Heartbeats counted

### Initial thinking 

Every service might want a generic `/info` endpoint.

This could serve up a JSON document with a combination of common and specific information about the service.

* Mem stats
* GC
* Uptime

Specifics might be things like how many pages a particular crawler processed, etc.

**Comment by jadudm** [comment]
An initial API endpoint containing a heartbeat was created for the `crawler`.

Extending it to include an endpoint with memory info would be easy. 

It should be close/ready to be made generic across multiple apps. A base router with `/heartbeat` and `/meminfo` can be complemented by the addition of app-specific routers layered on top (e.g. an endpoint to enqueue new jobs).

**Comment by jadudm** [comment]
Done.
