### ISSUE TITLE
:earth_americas: Terraform improvements

### ISSUE THREAD

**Issue by jadudm** [jadudm/eight#15]
### Tasks
- [ ] Any hardcoded value would need to be replaced with var.some_name
variables.tf will need to be updated
- [ ] Using a .tfvars file, you would simply need to store secrets in there and run with terraform plan -var-file="my.tfvars"
- [ ] you would likely need to convert it to be s3 partial configuration, like we do at FAC, just to ensure that the state can be accessible from the github runner (small change, not difficult) [Reference](https://github.com/GSA-TTS/FAC/blob/da8b61bdfabfebf9e23aed0f72508a7e12226a7a/terraform/sandbox/README.md#pre-configuration)
- [ ] mimic the FAC plan/apply stages (for handling S3 config)
